spring.application.name=ffmpeg-worker
spring.profiles.active=dev

spring.output.ansi.enabled=always

spring.jpa.open-in-view=false

# ============================ MinIO config ============================
minio.endpoint=http://localhost:9000
minio.public-url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=uniwise

# ============================ FFmpeg config ============================
ffmpeg.command-prefix=docker exec ffmpeg-service
ffmpeg.local-temp-dir=../../../../temp
ffmpeg.container-temp-dir=/temp

# ============================ RabbitMQ Listener config ============================
# Giới hạn số lượng message prefetch từ queue (RabbitMQ prefetch count)
spring.rabbitmq.listener.simple.prefetch=${SPRING_RABBITMQ_LISTENER_SIMPLE_PREFETCH:1}
# Giới hạn số lượng consumer thread xử lý đồng thời
spring.rabbitmq.listener.simple.concurrency=${SPRING_RABBITMQ_LISTENER_SIMPLE_CONCURRENCY:1}
spring.rabbitmq.listener.simple.max-concurrency=${SPRING_RABBITMQ_LISTENER_SIMPLE_MAX_CONCURRENCY:1}