# ============================ Threading config ============================
spring.threads.virtual.enabled=true
spring.main.keep-alive=true

# ============================ Server config ============================
server.port=9900

# ============================ RabbitMQ config ============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
