# ============================ Server config ============================
server.port=8086
server.servlet.context-path=/search-service
server.forward-headers-strategy=native

# ============================ Elasticsearch config ============================
spring.elasticsearch.uris=http://elasticsearch:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=000000

# ============================ Jwt Filter config ============================
jwt.public-key-path=classpath:keys/public.pem
jwt.token-header=X-Auth-Token
jwt.enabled=true

# ============================ RabbitMQ config ============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ============================ Redis config ============================
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=0000
spring.data.redis.username=default

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
