# ============================ Server config ============================
server.port=8086
server.servlet.context-path=/search-service
server.forward-headers-strategy=native

# ============================ Elasticsearch config ============================
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=000000

# ============================ Jwt Filter config ============================
jwt.public-key-path=classpath:keys/public.pem
jwt.token-header=X-Auth-Token
jwt.enabled=true

# ============================ RabbitMQ config ============================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
