spring.application.name=payment-service
spring.profiles.active=dev
spring.output.ansi.enabled=always
logging.pattern.console=%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(--- [%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

spring.jpa.open-in-view=false

# Lỗi thời gian
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
