# ============================ Mysql config ============================
spring.datasource.url=jdbc:mysql://mysql:3306/payment_service?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================ Redis config ============================
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=0000
spring.data.redis.username=default

# ============================ Server config ============================
server.port=8085
server.servlet.context-path=/payment-service
server.forward-headers-strategy=native

# ============================ Jwt Filter config ============================
jwt.public-key-path=classpath:keys/public.pem
jwt.token-header=X-Auth-Token
jwt.enabled=true

# ============================ RabbitMQ config ============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ============================ Grpc config ============================
grpc.clients.course-service.host=course-service
grpc.clients.course-service.port=9092
grpc.server.port=0


# ============================ VNPay Sandbox config ============================
vnpay.version=2.1.0
vnpay.command=pay
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmn-code=OQXNQEMM
vnpay.hash-secret=3MVH87HX7WNW0R5LMC3OSX7F0NLLNSN2
vnpay.return-url=http://localhost:3000/payment/result

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
