springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Route 0: Test
spring.cloud.gateway.server.webflux.routes[0].id=test
spring.cloud.gateway.server.webflux.routes[0].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/test/(?<segment>.*), /\${segment}

# Route 1
spring.cloud.gateway.server.webflux.routes[1].id=identity-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://identity-service:8000
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/identity-service/**
# spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/identity-service/(?<segment>.*), /\${segment}

# Route 2: User Service
spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://user-service:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/user-service/**
# spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/user-service/(?<segment>.*), /\${segment}