spring.application.name=gateway
spring.output.ansi.enabled=always
spring.main.web-application-type=reactive
spring.profiles.active=dev

server.tomcat.connection-timeout=60000
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=10000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=120s

logging.level.org.springframework.cloud.gateway=DEBUG
springdoc.swagger-ui.urls[0].name=identity-service
springdoc.swagger-ui.urls[0].url=/identity-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/user-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=course-service
springdoc.swagger-ui.urls[2].url=/course-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=media-service
springdoc.swagger-ui.urls[3].url=/media-service/v3/api-docs