# Route 0
spring.cloud.gateway.server.webflux.routes[0].id=test
spring.cloud.gateway.server.webflux.routes[0].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/test/(?<segment>.*), /\${segment}

# Route 1
spring.cloud.gateway.server.webflux.routes[1].id=identity-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8000
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/identity-service/**
# spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/identity-service/(?<segment>.*), /\${segment}