# ============================ Threading config ============================
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
grpc.server.virtual-threads.enabled=true

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ============================ Mysql config ============================
spring.datasource.url=jdbc:mysql://mysql:3306/identity_service?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
# Chỉ định Dialect thủ công nếu Hibernate không tự đoán được
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================ Redis config ============================
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=0000
spring.data.redis.username=default

# ============================ Server config ============================
server.port=8000
server.servlet.context-path=/identity-service
server.forward-headers-strategy=native

# ============================ Jwt Filter config ============================
jwt.public-key-path=classpath:keys/public.pem
jwt.token-header=X-Auth-Token
jwt.enabled=true

# ============================ Grpc config ============================
grpc.clients.user-service.host=user-service
grpc.clients.user-service.port=9091
