# Số lượng worker processes. Giá trị "auto" sẽ tự động dựa trên số CPU core.
# Để 1 để đơn giản cho môi trường dev, với production nên dùng auto.
worker_processes  1;

# Cấu hình event loop - xử lý kết nối bất đồng bộ
events {
    # Số kết nối tối đa mỗi worker có thể xử lý đồng thời
    worker_connections  1024;
}

# File log lỗi với mức debug - ghi lại tất cả các lỗi từ mức debug trở lên
# Mức log: debug > info > notice > warn > error > crit > alert > emerg
error_log  logs/error.log debug;

http {
    # Sử dụng DNS nội bộ của Docker (127.0.0.11) để phân giải tên container
    # ipv6=off: Tắt IPv6 vì môi trường Docker thường chỉ dùng IPv4
    # valid=30s: Cache kết quả DNS trong 30 giây trước khi query lại
    resolver 127.0.0.11 ipv6=off valid=30s;

    include       /usr/local/openresty/nginx/conf/mime.types;
    
    # Mặc định nếu không xác định được MIME type
    default_type  application/octet-stream;

    # Định nghĩa log định dạng JSON
    # 127.0.0.1 - - [24/Mar/2026:14:20:00 +0700] "GET /health HTTP/1.1" 200 2 "-" "PostmanRuntime/7.51.1" "-"
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # Khi cần ghi log, bỏ comment dòng dưới để ghi vào file
    # access_log  /var/log/nginx/access.log  main;

    # sendfile: Cho phép kernel gửi file trực tiếp từ disk ra socket
    # Giảm context switch giữa kernel và user space
    sendfile        on;

    # keepalive_timeout: Thời gian giữ kết nối TCP với client (tính bằng giây)
    # Giúp tái sử dụng kết nối cho nhiều request, giảm overhead TCP handshake
    keepalive_timeout  65;

    # Đường dẫn tìm kiếm các file Lua (.lua)
    # ;; ở cuối: Sau khi tìm trong path này, tiếp tục tìm trong path mặc định
    lua_package_path "/etc/nginx/lua/?.lua;;";

    # lua_shared_dict: Khai báo vùng nhớ chia sẻ giữa các worker để cache key
    lua_shared_dict secrets_key 1m;
    init_by_lua_file /etc/nginx/lua/init.lua;

    # Cấu hình Server
    server {
        listen       80;
        server_name  localhost;

        # 1. Route kiểm tra sức khỏe (Health Check)
        location /health {
            default_type text/plain;
            return 200 "OK";
        }

        # 2. Route chính sử dụng file Lua để kiểm tra quyền
        location / {
            # Gọi file Lua trong thư mục infra/nginx/lua/
            access_by_lua_file /etc/nginx/lua/access_check.lua;

            # Nếu Lua cho phép đi tiếp, proxy sẽ đẩy sang service khác
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_pass http://gateway-service:8080;
           # proxy_pass http://host.docker.internal:8080;
            
            # Tạm thời trả về nội dung nếu chưa có backend
            # default_type text/html;
            # content_by_lua_block {
            #     ngx.say("<p>Hello từ OpenResty! Lua da kiem tra xong.</p>")
            # }
        }

        # Trang báo lỗi
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }
    }
}