spring.application.name=media-service

spring.profiles.active=dev
spring.output.ansi.enabled=always
logging.pattern.console=%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(--- [%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

# Lỗi thời gian
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

# ============================ MinIO config ============================
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=${MINIO_BUCKET_NAME:uniwise}

# ============================ RabbitMQ config ============================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ============================ Multipart config ============================
# Giới hạn kích thước tối đa của một file tải lên
spring.servlet.multipart.max-file-size=200MB
# Giới hạn tổng kích thước request (bao gồm file + form field)
spring.servlet.multipart.max-request-size=250MB
# Giới hạn ghi file tạm thời xuống đĩa (file vượt quá kích thước này sẽ được ghi xuống đĩa thay vì giữ trên RAM)
spring.servlet.multipart.file-size-threshold=1MB

# ============================ Upload validation ============================
media.upload.thumbnail-max-size=10MB
media.upload.video-max-size=200MB
