spring.application.name=user-service
spring.profiles.active=dev
spring.output.ansi.enabled=always

spring.jpa.open-in-view=false

# Lỗi thời gian
spring.jackson.serialization.write-dates-as-timestamps=false